// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CleanupRoomReducer from "../cleanup_room_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import TriggerSoundReducer from "../trigger_sound_reducer";
import UpdateCursorReducer from "../update_cursor_reducer";
import UpdateSoundboardPolicyReducer from "../update_soundboard_policy_reducer";

export type CleanupRoomParams = __Infer<typeof CleanupRoomReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type TriggerSoundParams = __Infer<typeof TriggerSoundReducer>;
export type UpdateCursorParams = __Infer<typeof UpdateCursorReducer>;
export type UpdateSoundboardPolicyParams = __Infer<typeof UpdateSoundboardPolicyReducer>;

