// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomCode: __t.string(),
  watchUrl: __t.string(),
  ownerSessionId: __t.string(),
  ownerDisplayName: __t.string(),
  visibility: __t.string(),
  accessCode: __t.string(),
  soundboardMode: __t.string(),
  soundboardEnabled: __t.bool(),
  soundboardCapacity: __t.u16(),
};
