// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  strokeId: __t.string().primaryKey().name("stroke_id"),
  roomCode: __t.string().name("room_code"),
  sessionId: __t.string().name("session_id"),
  color: __t.string(),
  pointsJson: __t.string().name("points_json"),
  createdAtMs: __t.f64().name("created_at_ms"),
});
