// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  participantKey: __t.string().primaryKey().name("participant_key"),
  roomCode: __t.string().name("room_code"),
  sessionId: __t.string().name("session_id"),
  displayName: __t.string().name("display_name"),
  color: __t.string(),
  cursorX: __t.f32().name("cursor_x"),
  cursorY: __t.f32().name("cursor_y"),
  connectionId: __t.connectionId().name("connection_id"),
  lastSeenAtMs: __t.f64().name("last_seen_at_ms"),
});
