// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomCode: __t.string().primaryKey().name("room_code"),
  watchUrl: __t.string().name("watch_url"),
  watchHost: __t.string().name("watch_host"),
  visibility: __t.string(),
  accessCode: __t.string().name("access_code"),
  ownerSessionId: __t.string().name("owner_session_id"),
  ownerDisplayName: __t.string().name("owner_display_name"),
  soundboardMode: __t.string().name("soundboard_mode"),
  autoSoundboardCapacity: __t.u16().name("auto_soundboard_capacity"),
  manualSoundboardEnabled: __t.bool().name("manual_soundboard_enabled"),
  manualSoundboardCapacity: __t.u16().name("manual_soundboard_capacity"),
  createdAtMs: __t.f64().name("created_at_ms"),
  lastActivityAtMs: __t.f64().name("last_activity_at_ms"),
  archived: __t.bool(),
});
