// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  roomCode: __t.string().name("room_code"),
  sessionId: __t.string().name("session_id"),
  actorDisplayName: __t.string().name("actor_display_name"),
  soundId: __t.string().name("sound_id"),
  createdAtMs: __t.f64().name("created_at_ms"),
});
