// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Participant = __t.object("Participant", {
  participantKey: __t.string(),
  roomCode: __t.string(),
  sessionId: __t.string(),
  displayName: __t.string(),
  color: __t.string(),
  cursorX: __t.f32(),
  cursorY: __t.f32(),
  connectionId: __t.connectionId(),
  lastSeenAtMs: __t.f64(),
});
export type Participant = __Infer<typeof Participant>;

export const Room = __t.object("Room", {
  roomCode: __t.string(),
  watchUrl: __t.string(),
  watchHost: __t.string(),
  visibility: __t.string(),
  accessCode: __t.string(),
  ownerSessionId: __t.string(),
  ownerDisplayName: __t.string(),
  soundboardMode: __t.string(),
  autoSoundboardCapacity: __t.u16(),
  manualSoundboardEnabled: __t.bool(),
  manualSoundboardCapacity: __t.u16(),
  createdAtMs: __t.f64(),
  lastActivityAtMs: __t.f64(),
  archived: __t.bool(),
});
export type Room = __Infer<typeof Room>;

export const SoundEvent = __t.object("SoundEvent", {
  eventId: __t.string(),
  roomCode: __t.string(),
  sessionId: __t.string(),
  actorDisplayName: __t.string(),
  soundId: __t.string(),
  createdAtMs: __t.f64(),
});
export type SoundEvent = __Infer<typeof SoundEvent>;

